## Nextcloud configuration
nextcloud:
  host: nextcloud.home
  username: admin
  password: admin-password
  update: 0
  datadir: /var/www/html/data
  subPath: nextcloud

image:
  # flavor: fpm
  # tag: 31.0.2-fpm-alpine
  # NOTE: set after working
  pullPolicy: Always

## Persistence configuration
persistence:
  enabled: true
  # existingClaim: ""
  storageClass: truenas-nfs
  accessMode: ReadWriteMany
  size: 256Gi

  nextcloudData:
    enabled: true
    storageClass: truenas-nfs
    accessMode: ReadWriteMany
    size: 6Gi

## Ingress configuration
ingress:
  enabled: true
  className: nginx-internal
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
    - "nextcloud.home"

service:
  loadBalancerIP: 192.168.50.130
  annotations:
    metallb.universe.tf/allow-shared-ip: nextcloud-svc
  type: LoadBalancer

## Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi

## MariaDB configuration
mariadb:
  enabled: true
  auth:
    rootPassword: mariadb-root-password
    password: mariadb-user-password
  primary:
    persistence:
      enabled: true
      storageClass: truenas-nfs
      accessMode: ReadWriteOnce
      size: 8Gi
# NOTE: uncomment after first setup.
# https://github.com/nextcloud/helm/issues/259#issuecomment-1203159235
# cronjob:
#   enabled: false
# livenessProbe:
#   enabled: false
# readinessProbe:
#   enabled: false
startupProbe:
  enabled: true
