## Nextcloud configuration
nextcloud:
  host: nextcloud.home
  username: admin
  password: admin-password
  update: 0
  datadir: /var/www/html/data

## Persistence configuration
persistence:
  enabled: true
  # existingClaim: ""
  storageClass: "nas-nextcloud"
  accessMode: ReadWriteMany
  size: 495Gi

  nextcloudData:
    enabled: true
    storageClass: "nas-nextcloud"
    accessMode: ReadWriteMany
    size: 5Gi

## Ingress configuration
ingress:
  enabled: true
  className: nginx-internal
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
    - "nextcloud.home"

## Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi

## MariaDB configuration
mariadb:
  enabled: true
  auth:
    rootPassword: mariadb-root-password
    password: mariadb-user-password
  primary:
    persistence:
      enabled: true
      storageClass: "nfs-storage"
      accessMode: ReadWriteOnce
      size: 10Gi
