---
persistentVolumeClaim:
  enabled: true

ingress:
  enabled: true
  hosts:
    - "pihole.home"

serviceWeb:
  loadBalancerIP: 192.168.50.130
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.50.130
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

replicaCount: 1
